#!/usr/bin/env bash
# Create a .pid file on /var/run and this process can be killed
handle_sigterm() {
    echo "I hate the kill command"
}

handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
    rm -f /var/run/myscript.pid
    exit 0
}
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

echo $$ > /var/run/myscript.pid

echo "To infinity and beyond indefinitely"
while true; do
    sleep 1
done
